### ISSUE TITLE
A little problem with run example

### ISSUE THREAD

**Issue by bearjr** [Polyneue/behance-api#15]
Maybe it's stupid, but I just started with React and it will be helpful for me: where exactly I should paste my token? I try to change API_KEY but I still don't really understand error about api.json file {Cannot find module '../api.json'}, what should I do to run example?

**Comment by Polyneue** [comment]
Hi @bearjr -- the example directory is for working within the module itself. If you are going to be using the behance-api as a dependency of your project, you should refer to the usage example in the readme https://github.com/Polyneue/behance-api#usage:

```javascript
const Behance = require('behance-api'); // The Behance API module
const Be = new Behance(API_KEY); // Instantiate a connection to Behance 

// Get Projects Data
Be.projects({q: 'motorcycle'}, function (err, res, data) {
  if (err) throw err;

  // Do something with the data received from the API
  console.dir(data);
});
```

You'll want to swap the `API_KEY` with whatever your API string is from Behance. 

---
If you just want to run the example, swap `line 3` of the example file with:
```javascript
const API_KEY = 'MY_API_KEY_HERE';
```
